services:
  service:
    image: '${DOCKER_IMAGE_NAME}:latest'
    container_name: '${DOCKER_CONTAINER_NAME}'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1.6G
        reservations:
          cpus: '0.25'
          memory: 200M
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true